# Generated by Django 5.0.6 on 2024-05-28 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(
                max_length=100,
                verbose_name="Действие, которое представляет собой привычка.",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.PositiveIntegerField(
                default=1,
                verbose_name="периодичность выполнения привычки для напоминания в днях.",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(
                max_length=100, verbose_name="Место, где необходимо выполнять привычку"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="pleasantness",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Привычка, которую можно привязать к выполнению полезной привычки.",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="public",
            field=models.BooleanField(
                default=False,
                verbose_name="привычки можно публиковать в общий доступ, "
                "чтобы другие пользователи могли брать в пример чужие привычки.",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habits.habit",
                verbose_name="привычка, которая связана с другой привычкой, "
                "важно указывать для полезных привычек, но не для приятных",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="чем пользователь должен себя вознаградить после выполнения.",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                verbose_name="Время, когда необходимо выполнять привычку."
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time_required",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="время, которое предположительно потратит пользователь на выполнение привычки.",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель привычки",
            ),
        ),
    ]
