# Generated by Django 5.0.6 on 2024-05-28 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=100)),
                ("time", models.TimeField()),
                ("action", models.CharField(max_length=100)),
                (
                    "pleasantness",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("frequency", models.PositiveIntegerField(default=1)),
                ("reward", models.CharField(blank=True, max_length=100, null=True)),
                ("time_required", models.IntegerField(blank=True, null=True)),
                ("public", models.BooleanField(default=False)),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habbits.habit",
                    ),
                ),
            ],
        ),
    ]
